steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/woolworths-beam:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/woolworths-beam:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud auth configure-docker --quiet
    # Build flex template (example)
    gcloud dataflow flex-template build gs://woolworths-data-$PROJECT_ID/templates/sales_flex_template.json               --image gcr.io/$PROJECT_ID/woolworths-beam:latest               --sdk-language "PYTHON"               --flex-template-base-image "gcr.io/dataflow-templates-base/python3-template-launcher-base"
images:
- 'gcr.io/$PROJECT_ID/woolworths-beam:latest'
